### ISSUE TITLE
Font Style Problem

### ISSUE THREAD

**Issue by jarieagito** [jarieagito/modularity-mindfulness#1]
Hi Jess.
Here's a screenshot of the type issue I've been having. 
@JessJodoin
<img width="813" alt="Screen Shot 2020-09-26 at 2 18 08 PM" src="https://user-images.githubusercontent.com/55108790/94347543-26c0bf00-0003-11eb-9492-2d98d78a6137.png">

**Comment by JessJodoin** [comment]
I opened in Firefox and the italic isn't there.
When you throw it in Markbot, does the italics show up?

**Comment by jarieagito** [comment]
Markbot doesn't say there's any italics but it shows on the screenshots in Markbot. Should I relaunch the website on a different browser?
@JessJodoin

**Comment by JessJodoin** [comment]
It's strange that they show on the Markbot screen comparison. I downloaded the zip of your repo just to see, and they didn't show up when I put it in Markbot. Weird.

@hellachella What do you think?

**Comment by jarieagito** [comment]
Yeah, markbot's still showing me it's italics even when I switch it to a different browser and reloaded it. I'm not sure why. 

@JessJodoin @hellachella

**Comment by hellachella** [comment]
Taking a look.

**Comment by hellachella** [comment]
Also downloaded it and I'm not seeing italics.

<img width="317" alt="Screen Shot 2020-09-28 at 10 12 05 AM" src="https://user-images.githubusercontent.com/10465921/94443508-3eb75080-0173-11eb-82a5-a5d1a3f28c8b.png">

**Comment by hellachella** [comment]
put ```font-style: normal; ``` and ```font-weight: normal;```  in the css for your header. See if that does it.

**Comment by jarieagito** [comment]
It's still italics for me in Markbot. I'm unsure why in Firefox it's italicized but other browsers it's not.

<img width="326" alt="Screen Shot 2020-09-28 at 10 37 01 AM" src="https://user-images.githubusercontent.com/55108790/94447404-b7201080-0177-11eb-9625-e8e27bfca903.png">

@hellachella

**Comment by hellachella** [comment]
Are you by any chance using a PC?

**Comment by jarieagito** [comment]
No I'm using the Macbook Pro @hellachella

**Comment by jarieagito** [comment]
<img width="323" alt="Screen Shot 2020-09-30 at 8 33 41 AM" src="https://user-images.githubusercontent.com/55108790/94685628-b1e9cf80-02f7-11eb-8378-4c2cec0b292a.png">

It's still having that issue :(
@hellachella
@JessJodoin

**Comment by hellachella** [comment]
Looking into it

**Comment by hellachella** [comment]
Try setting up your banner and sections as such:

```
  <main>

    <img src="" alt="">
    <div class="">
      <!-- Intro info etc -->
    </div>

    <section> <!-- display grid -->

      <article class="">
        <!-- content -->
      </article>

      <article class="">
        <!-- content -->
      </article>

      <article class="">
        <!-- content -->
      </article>

    </section>

  </main>
```

I think your CSS is confused because you have put the image and headers into a section. Also, instead of using `divs` for the cards, use `articles`.

**Comment by JessJodoin** [comment]
Has this been solved? If so, could you close this issue? 😄
